collections: 
  projects:
    output: true
    permalink: /projects/:name
  resume_entries:
    output: true
    permanlink: /resume/:name
  archives:
    output: true
    permalink: /archives/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "entry"
